language: r

services:
  - elasticsearch

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  slack:
    secure: YOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=
  email:
    on_success: change
    on_failure: change
