language: c

sudo: required

env:
  matrix:
  - ES_VERSION=1.7.2
  - ES_VERSION=2.0.0 

before_install:
  - case "$ES_VERSION" in
    "") ;;

    "1.7.2")
      export ES_VERSION=1.7.2 ;
      curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "2.0.0")
      export ES_VERSION=2.0.0 ;
      curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ES_VERSION/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start 
      ;;
   esac

  - sleep 3
  - sudo service elasticsearch status
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - "./pkg-build.sh bootstrap"

install:
- "./pkg-build.sh install_deps"
- "./pkg-build.sh install_github jimhester/covr"

script:
- "./pkg-build.sh run_tests"

after_failure:
- "./pkg-build.sh dump_logs"

after_success:
- if [[ ! -z "$COVERAGE" ]];then ./pkg-build.sh run_script -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: TyJn718GQw/lQE0v9QzTRMU2aXppaw65oyfUxfDa7KYjsgfqY0Hq+H3I71bUxBlnUNnW5Hsxm+b+YiaNDEZ2UmJJLr4X34r5mRRABy94nTs7YYLIE2ugtXb1BQArxaFo1HNBm1xNg+CCLWdvfQ6wR7PhT08CuGwwejAr97y5xTQ=
