language: c

sudo: required

services:
- elasticsearch

before_script:
- sleep 5

before_install:
- curl "http://127.0.0.1:9200"
- curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
- chmod 755 pkg-build.sh
- "./pkg-build.sh bootstrap"

install:
- "./pkg-build.sh install_deps"
- "./pkg-build.sh install_github jimhester/covr"

script:
- "./pkg-build.sh run_tests"

after_failure:
- "./pkg-build.sh dump_logs"

after_success:
- if [[ ! -z "$COVERAGE" ]];then ./pkg-build.sh run_script -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: TyJn718GQw/lQE0v9QzTRMU2aXppaw65oyfUxfDa7KYjsgfqY0Hq+H3I71bUxBlnUNnW5Hsxm+b+YiaNDEZ2UmJJLr4X34r5mRRABy94nTs7YYLIE2ugtXb1BQArxaFo1HNBm1xNg+CCLWdvfQ6wR7PhT08CuGwwejAr97y5xTQ=
