language: r

env:
  matrix:
  - ES_VERSION=2.0.0
  - ES_VERSION=2.1.0
  - ES_VERSION=2.1.1

before_install:
  - case "$ES_VERSION" in
    "") ;;

    "2.0.0")
      export ES_VERSION=2.0.0 ;
      curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ES_VERSION/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start 
      ;;
      
    "2.1.0")
      export ES_VERSION=2.1.0 ;
      curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ES_VERSION/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start 
      ;;
      
    "2.1.1")
      export ES_VERSION=2.1.1 ;
      curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ES_VERSION/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start 
      ;;
   esac

  - sleep 3
  - sudo service elasticsearch status

r_github_packages:
- jimhester/covr

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: TyJn718GQw/lQE0v9QzTRMU2aXppaw65oyfUxfDa7KYjsgfqY0Hq+H3I71bUxBlnUNnW5Hsxm+b+YiaNDEZ2UmJJLr4X34r5mRRABy94nTs7YYLIE2ugtXb1BQArxaFo1HNBm1xNg+CCLWdvfQ6wR7PhT08CuGwwejAr97y5xTQ=
Status API Training Shop Blog About Pricing
